name: Train and Register Model

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install DVC  
        uses: iterative/setup-dvc@v2

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install mlflow imbalanced-learn

      - name: Cache dataset
        uses: actions/cache@v3
        id: cache-dataset
        with:
          path: data/raw/healthcare-dataset-stroke-data.csv
          key: dataset-${{ hashFiles('data/raw/healthcare-dataset-stroke-data.csv.dvc') }}

      - name: Download dataset if cache miss
        if: steps.cache-dataset.outputs.cache-hit != 'true'
        run: |
          echo "Dataset not in cache â€“ please upload it once using Cara #1"
          echo "Atau gunakan remote storage"
          exit 1

      - name: Reproduce pipeline
        run: dvc repro

      - name: Upload model terbaru
        uses: actions/upload-artifact@v4
        with:
          name: model-latest
          path: model/artifacts/latest/